image:
- Ubuntu

install:
- sh: sudo apt-get -q update
- sh: sudo apt-get -qy --no-install-recommends install libpcre3-dev libgit2-dev

build_script:
- sh: make

after_build:
- sh: zip ff-linux.zip ff

artifacts:
- path: ff-*.zip
  name: binary
