image:
- Visual Studio 2015
- Ubuntu

install:
- cmd: C:\cygwin64\setup-x86_64.exe -nqP libgit2-devel,libpcre-devel
- sh: sudo apt-get -q update
- sh: sudo apt-get -qy --no-install-recommends install libpcre3-dev libgit2-dev

build_script:
- cmd: C:\cygwin64\bin\sh -lc "cd c:/projects/ff; make"
- sh: make

after_build:
- cmd: 7z a ff-win.zip ff.exe C:\cygwin64\bin\cygwin1.dll C:\cygwin64\bin\cyggit2-25.dll C:\cygwin64\bin\cygpcre-1.dll
- sh: zip ff-linux.zip ff

artifacts:
- path: ff-*.zip
  name: binary
